### PR TITLE
Add first draft of Code Review page

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen Ready for (sort of code) Review! :D

**Comment by avermeulen** [comment]
I like it. Happy to go with it - you wanna a link to it from the Make your code better page?

**Comment by SteveBarnett** [comment]
@avermeulen Yes! Not sure of the best place, though... Suggestions, please?

**Comment by SteveBarnett** [comment]
@avermeulen Ready for re-review.

**Comment by SteveBarnett** [comment]
Verbal :+1: from Dr Dre, so merging it in.

**Pull request merged**
